apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-bench
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kube-bench
            image: docker.io/aquasec/kube-bench:v0.6.11
            command: ["kube-bench"]
            volumeMounts:
            - name: config-volume
              mountPath: /etc/kubernetes
          restartPolicy: Never
          volumes:
          - name: config-volume
            configMap:
              name: kube-bench-config
  successfulJobsHistoryLimit: 3
