apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-hunter
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            environment: production
          containers:
          - name: kube-hunter
            image: docker.io/aquasec/kube-hunter:0.6.8
            command: ["kube-hunter"]
            args: ["--pod"]
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
