apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: my-slack-image
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#argocd-jobs\", \"username\": \"argoCDAdmin\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":200w:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2
