apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmChart
metadata:
  name: nginx
  namespace: default
spec:
  chart: nginx
  sourceRef:
    kind: GitRepository
    name: nginx
    namespace: default
  interval: 1m
  values:
    replicaCount: 1
