apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmChart.yml
patchesStrategicMerge:
  - overlays/dev/values.yaml
  - overlays/stg/values.yaml
  - overlays/prod/values.yaml
